### ISSUE TITLE
Boost dependency

### ISSUE THREAD

**Issue by jgphpc** [MeteoSwiss-APN/comm_overlap_bench#11]
Is it be possible to compile without Boost ?
> #ifndef _NOBOOST

**Comment by pspoerri** [comment]
No, that's not possible. But you can avoid adding the boost libraries by specifying `-DENABLE_TIMER=OFF`.

**Comment by pspoerri** [comment]
I added it earlier today.

**Comment by jgphpc** [comment]
https://github.com/MeteoSwiss-APN/comm_overlap_bench/blob/barebones/src/CMakeLists.txt#L72

**Comment by jgphpc** [comment]
Reopening this issue to be sure that all dependency with Boost are removed:
@pspoerri   Is it possible to compile the code without these lines ?

```c++
src/HoriDiffRepository.cpp:9:#include <boost/make_shared.hpp>
src/HoriDiffRepository.cpp:25:        horiDiffFields_.push_back(
 boost::make_shared<SwapDataField<IJKRealField> >());

src/HoriDiffRepository.h:14:#include <boost/shared_ptr.hpp>
src/HoriDiffRepository.h:27:    BOOST_STATIC_ASSERT(N_HORIDIFF_VARS > 0);
src/HoriDiffRepository.h:83:    std::vector< boost::shared_ptr
  < SwapDataField<IJKRealField> > >& horiDiffFields() { return horiDiffFields_; }
src/HoriDiffRepository.h:100:    std::vector<boost::shared_ptr
  < SwapDataField<IJKRealField> > > horiDiffFields_;
```

**Comment by jgphpc** [comment]
On Kesch, when Boost modulefile is not loaded, makefile will find it anyway:
`/usr/include/boost/shared_ptr.hpp`
=> adding -D_NO_BOOST macro.
PR https://github.com/MeteoSwiss-APN/comm_overlap_bench/pull/16
