### ISSUE TITLE
nvprof on kesch (pow in Kernel.cu)

### ISSUE THREAD

**Issue by jgphpc** [MeteoSwiss-APN/comm_overlap_bench#23]
Trying to explain https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/6#issuecomment-292551671

## MVAPICH2/2.2-GCC-4.9.3-binutils-2.25 + cuda/7.0

> module load craype-haswell 
> module load craype-network-infiniband 
> module load MVAPICH2/2.2-GCC-4.9.3-binutils-2.25 

```
Currently Loaded Modulefiles:
  1) craype-haswell                         3) binutils/.2.25                         5) cudatoolkit/7.0.28
  2) craype-network-infiniband              4) GCC/4.9.3-binutils-2.25                6) MVAPICH2/2.2-GCC-4.9.3-binutils-2.25
```

> export MV2_USE_CUDA=1 
> srun -p debug --gres=gpu:1 -N1 -n1 --ntasks-per-node=1 -t15 \ 
> nvprof --analysis-metrics -o my.nv \ 
> ./GNU4.9.3_MVAPICH22.2_CUDAV7.0.27.keschln-0002+setdev 

## MVAPICH2/2.2-GCC-4.9.3-binutils-2.25 + cuda/7.5

> module load craype-haswell 
> module load craype-network-infiniband 
> module load MVAPICH2/2.2-GCC-4.9.3-binutils-2.25-cuda75

```
Currently Loaded Modulefiles:
  1) craype-haswell                                 3) binutils/.2.25                                 5) cudatoolkit/7.5.18
  2) craype-network-infiniband                      4) GCC/4.9.3-binutils-2.25                        6) /MVAPICH2/2.2-GCC-4.9.3-binutils-2.25-cuda75
```

> export MV2_USE_CUDA=1 
> srun -p debug --gres=gpu:1 -N1 -n1 --ntasks-per-node=1 -t15 \ 
> nvprof --analysis-metrics -o my.nv \ 
> ./GNU4.9.3_MVAPICH22.2_CUDAV7.5.17.keschln-0001+setdev

**Comment by jgphpc** [comment]
### MVAPICH2/2.2-GCC-4.9.3-binutils-2.25 + cuda/7.0
> srun -p debug --gres=gpu:1 -N1 -n1 --ntasks-per-node=1 -t10 \ 
> nvprof --analysis-metrics -o o_4.nv \ 
> ./GNU4.9.3_MVAPICH22.2_CUDAV7.0.27.keschln-0002+setdev -n 4 &> o_nv4
* where -n 4 means 4 steps.

### MVAPICH2/2.2-GCC-4.9.3-binutils-2.25 + cuda/7.5
> srun -p debug --gres=gpu:1 -N1 -n1 --ntasks-per-node=1 -t10 \ 
> nvprof --analysis-metrics -o o_4.nv \ 
> ./GNU4.9.3_MVAPICH22.2_CUDAV7.5.17.keschln-0001+setdev -n 4 &> o_nv4

### nvprof reports (-n 2, MAX values)
* in  kesch:/scratch/piccinal/comm_overlap_bench.gitjg/KESCH+MVAPICH22+CUDA7*/

![eff](https://cloud.githubusercontent.com/assets/5328644/24914166/b45f8bb2-1ed3-11e7-96a4-6f0a6ae16c7b.png)

* KESCH+MVAPICH22+CUDA70
```
o_10.steps:ELAPSED TIME (seconds) for rank=0 0.047673
o_20.steps:ELAPSED TIME (seconds) for rank=0 0.086307
o_40.steps:ELAPSED TIME (seconds) for rank=0 0.161041
o_80.steps:ELAPSED TIME (seconds) for rank=0 0.300822
o_100.steps:ELAPSED TIME (seconds) for rank=0 0.354515
o_200.steps:ELAPSED TIME (seconds) for rank=0 0.638713
```

* KESCH+MVAPICH22+CUDA75 (slower than cuda/70)
```
o_10.steps:ELAPSED TIME (seconds) for rank=0 0.089471
o_20.steps:ELAPSED TIME (seconds) for rank=0 0.141826
o_40.steps:ELAPSED TIME (seconds) for rank=0 0.343104
o_80.steps:ELAPSED TIME (seconds) for rank=0 0.729038
o_100.steps:ELAPSED TIME (seconds) for rank=0 0.868396
o_200.steps:ELAPSED TIME (seconds) for rank=0 1.590747
```

**Comment by cosunae** [comment]
this is indeed very puzzling, why such an increase of instructions...

can you post the assembly or ptx? 
cuobjdump --dump-sass

**Comment by cosunae** [comment]
there is a power function, another option would be to comment it out or replace it with a simple sum and compare 70 and 75 again? could be a good candidate also for the missmatch in number of instructions.

**Comment by jgphpc** [comment]
See kesch:/scratch/piccinal/comm_overlap_bench.gitjg/KESCH+MVAPICH22+CUDA7*/o_cuobjdump

**Comment by jgphpc** [comment]
https://webrt.cscs.ch/Ticket/Display.html?id=27306

**Comment by jgphpc** [comment]
Fixed in https://github.com/MeteoSwiss-APN/comm_overlap_bench/pull/26

**Comment by jgphpc** [comment]
### Why is cuda/70 faster than cuda/75 ?

While compiling src/Kernel.cu with `-D_NOPOW` helps making cuda/75 faster:

| cuda/75 | G2G=1 |
|-------------|-------|
| with pow()      |7.39 sec|
| without pow() |3.62 sec|

cuda/75 remains slower than cuda/70:

| G2G=1 | | -n 3000 (steps)|
|-------------|-------|---|
| cuda/70| 3.26 sec|9.50 sec|
| cuda/75| 3.72 sec|10.84 sec|

Can nvprof explain why ?

### nvprof reports (-n 2 steps, compiling with -D_NOPOW)

> srun -p debug --gres=gpu:1 -N1 -n1 --ntasks-per-node=1 --distribution=block:block \\
> --cpu_bind=q -t2 \\
> nvprof --analysis-metrics -o o.nv \\
> ./GNU4.9.3_MVAPICH2-GDR2.1_CUDAV7.0.27.keschln-0001 -n 2
or
> ./GNU4.9.3_MVAPICH2-GDR2.2_CUDAV7.5.17.keschln-0001 -n 2
then
> nvprof --csv -i o.nv &> o.csv

* cuda/75 slowness may come from lower `DP FP` instructions or higher `bit-convert` instructions (?):
   * column1: metric name
   * column2: cuda/75
   * column3: cuda/70
   * column4: cuda/75-cuda/70
```
inst_fp_64                              85646590                36641437             49005153
flop_count_dp_fma                       47629951                9031969             38597982
inst_misc                               23573252                13166180             10407072
flop_count_dp_add                       19447414                13225149              6222265
inst_issued                             10620619                6703238              3917381
issue_slots                             9496109                 5881934              3614175
flop_count_dp_mul                       9249132                 5785979              3463153

achieved_occupancy              0.591177                0.588974   0.002203

ldst_issued                             793702                  808773               -15071
cf_issued                               706379                  724424               -18045
inst_bit_convert                        0                       298536              -298536
```

How to link this to https://github.com/MeteoSwiss-APN/comm_overlap_bench/blob/barebones/src/Kernel.cu ?

**Comment by jgphpc** [comment]
Latest results on kesch (timings in seconds) after PR https://github.com/MeteoSwiss-APN/comm_overlap_bench/pull/34 (no pow, no exp, no log):



* srun -p debug --gres=gpu:2 -N1 -n2 --ntasks-per-node=2 ./GNU -n 3000

| mvapich2gdr | G2G=1 | G2G=2 |
|-------------|-------|-------|
| cuda/70     |8.16  |8.31 |
| cuda/75     |8.64 |9.24 |
