### ISSUE TITLE
using GDR gpu communication (G2G=2) shows a large performance degradation with full node

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/comm_overlap_bench#27]
In KESCH: 
in the past we always observed good results with G2G=2 (using the GDR driver) but we could never put that in production due to the bug with CCE environment. 
But the bug will presumably be fixed with the upgrade of kesch, so we would like to switch to G2G=2.

However the recent experiments of @pspoerri 
https://docs.google.com/spreadsheets/d/1xmL4-qsGpeDdb7qi-85fq2sl-7dCdECztR9Y-YaOX04/edit#gid=0
shows a large degradation in performance once  we cross the QPI, (i.e. jobs using full node)

**Comment by jgphpc** [comment]
https://webrt.cscs.ch/Ticket/Display.html?id=27848

**Comment by pspoerri** [comment]
Here are two sample runs that I just did to highlight the problems:
- [CUDA 7.0, 16 Jobs, G2G=1](https://gist.github.com/pspoerri/e1c08a9464bd6cf5e4e813b7db9c7687)
- [CUDA 7.0, 16 Jobs, G2G=2](https://gist.github.com/pspoerri/3cbc1e9b031f11bbcc83076f3d5ba6c8)

A good explanation of the Kesch system can be found in [this presentation](https://spcl.inf.ethz.ch/Publications/.pdf/multigpu_pcie_bw_model_slides.pdf) by Maxime.

**Comment by pspoerri** [comment]
To put the issue in words: As soon as the GPUs have to communicate over the QPI with G2G=2 enabled (all GPUs see each other) then we have an explosion in the runtime of the application.

**Comment by jgphpc** [comment]
Here are my timings using default benchmark (in seconds):

> G2G=1 jobs=$i 
> ../run_kesch.sh ./GNU4.9.3_MVAPICH2-GDR2.1_CUDAV7.0.27.keschln-0003

### default
| cuda/70 | G2G=1 |nocomm|nocomp|
|-------------|-------|-------|-------|
|1|2.90738|2.51745|     0.379765|
|2|2.87979|2.54601|     1.0765|
|4|4.18487|2.47546|     2.53616|
|8|5.01914|2.47683|     3.54143|
|16|5.67805|2.54346|    4.25761|

* communication cost (nocomp) increases with number of tasks while computation cost (nocomm) remains constant.

@pspoerri What is the difference between `CUDA_VISIBLE_DEVICES` and `Configured CUDA Devices` ?

```
MV2_COMM_WORLD_LOCAL_RANK: 0, 1, 
CUDA_VISIBLE_DEVICES: [0: 0] [1: 1] 
Configured CUDA Devices: [0: 0] [1: 0] 
SLURM_JOBID: 1875917
SLURM_PROCID: 0, 1, 
SLURM_CPU_BIND: 
[0: quiet,mask_cpu:0x000001,0x000002] 
[1: quiet,mask_cpu:0x000001,0x000002] 
SLURMD_NODENAME: keschcn-0002, keschcn-0002, 
MV2_USE_CUDA: 1
ELAPSED TIME (seconds) for rank=0 8.072012
ELAPSED TIME (seconds) for rank=1 8.072035
```

| cuda/70 | G2G=2 |nocomm|nocomp|
|-------------|-------|-------|-------|
|1|2.83478|2.51806| 0.328088|
|2|2.87262|2.49982| 1.02162|
|4|4.69077|2.484|   3.09187|
|8|4.97395|2.51271| 3.4996|
|16|35.0311|2.53712| 34.0035|

### -n 3000 (steps)

| cuda/70 | G2G=1 |nocomm|nocomp|
|-------------|-------|-------|-------|
|1|8.40565|     7.34751|0.931054|
|2|8.21832|     7.37986|2.99022|
|4|12.1826|     7.36005|7.50626|
|8|14.6379|     7.37286|10.1471|
|16|16.3243|    7.37515|12.0165|

| cuda/70 | G2G=2 |nocomm|nocomp|
|-------------|-------|-------|-------|
|1|10.2431|     7.37224|  0.911356|
|2|8.12892|     7.30711|  2.97307|
|4|13.9674|     7.3954|   9.20228|
|8|49.0711|     7.41947|  27.0633|
|16|105.007|    7.44763|  102.046|

**Comment by pspoerri** [comment]
Hint: Maybe force `MV2_CUDA_IPC=0`
