### ISSUE TITLE
kesch: segfault in MPI_Finalize 

### ISSUE THREAD

**Issue by jgphpc** [MeteoSwiss-APN/comm_overlap_bench#3]
Hi,

This is my first attempt to run StandaloneStencilsCUDA. 

> export G2G=2
> srun -p debug --gres=gpu:2 -n2 -t10 ./StandaloneStencilsCUDA

Unfortunately, i get a segfault at the very end of the job (in MPI_Finalize):

```
Domain : [128,128,60]
Sync? : 0
NoComm? : 0
NoComp? : 0
Number Halo Exchanges : 2
Number benchmark repetitions : 1000
In Order halo exchanges? : 0
Device ID :0
SLURM_PROCID :0
Compiled for mvapich2
ELAPSED TIME : ...
[keschcn-0001:mpi_rank_0][error_sighandler] 
Caught error: Segmentation fault (signal 11)
```

### mvapich2gdr_gnu/2.1_cuda_7.0
> ELAPSED TIME : 3.1743 +- + 0.00574198

@pspoerri do you get the same segfault ? If not, could you point to 2 successful jobs (1 with and 1 without aysnchronous mode) ?

### mvapich2gdr_gnu/2.2_cuda_7.5
I don't segfault with cuda/75:
> ELAPSED TIME : 8.4395 +- + 0.00154042

**Comment by jgphpc** [comment]
### mvapich2gdr_gnu/2.2_cuda_7.5
Another issue is how to compile the code: if `libmpi.so` is at the end of the link line, the code will segfault BUT if `libmpi.so` is moved just after `-lcudart_static` then job will run fine. 
Do you know how to do that with `cmake` ?

**Comment by pspoerri** [comment]
@jgphpc, yes. I can confirm: I'm getting the same segfaults when I run with `G2G=1`.
I just checked the way we compile STELLA and there we link MPI with a separate library which is then linked into the Dycore. I can have a look into this.

**Comment by jgphpc** [comment]
Will continue the discussion in separate issues.
