### ISSUE TITLE
write_buffer%completed error

### ISSUE THREAD

**Issue by jgphpc** [MeteoSwiss-APN/comm_overlap_bench#35]
@mmxcscs is trying to use MUST (=MPI runtime checker) on cosmo (only the non-gpu build compiled
with GNU for now). MUST detects a conflict between active buffers in MPI_Irecv from mpe_io2.f90.
Unfortunately, COSMO crashes with the following error:

```
At line 2178 of file /scratch-shared/meteoswiss/scratch/maximem/mpi1sided/
cosmo-pompa_debug/cosmo/src/mpe_io2.f90

Fortran runtime error: Index '999999' of dimension 1 of array
'write_buffer%completed' above upper bound of 7
```

Both the crash and the MPI_irecv issue seem to be related. Have you ever seen
that crash before ? That could also be a glitch of the tool.

**Comment by jgphpc** [comment]
![eff](https://user-images.githubusercontent.com/5328644/27543854-b45a4064-5a8b-11e7-88a8-ab9582c28dad.png)

**Comment by pspoerri** [comment]
I start to suspect why we see this error.

**Comment by pspoerri** [comment]
The MPI communication is provided by GCL/STELLA once the C++ Dycore is used. If we are seeing such an error after the C++ Dycore startup then I guess we have an issue with the Fortran code base. @ofuhrer @cosunae can you confirm this?
Would we need to use the GCL Communication wrapper there?

**Comment by cosunae** [comment]
Are you sure this is connected to GCL? The report here has to do with mpi communication related to IO, which is not handled by GCL/STELLA. 
So I think unless there is a clash of tags it wont be related to GCL. 
@jgphpc @mmxcscs could you try to switch off IO in cosmo to see if this is the issue of the crash of 1 sided

**Comment by ofuhrer** [comment]
PS. Switching off I/O (or better O) is done by setting ngribout=0 in the IOCTL namelist block in INPUT_IO.

**Comment by mmxcscs** [comment]
Valgrind is also reporting something not correct in that part of the code:
``` OPEN: grb1-file: ./input/laf2015062112^M
==8070== Uninitialised byte(s) found during client check request
==8070==    at 0xEB988CD: check_mem_is_defined_untyped (libmpiwrap.c:953)
==8070==    by 0xEB9A48F: walk_type_array (libmpiwrap.c:909)
==8070==    by 0xEB9A48F: check_mem_is_defined (libmpiwrap.c:995)
==8070==    by 0xEB9A48F: generic_Send (libmpiwrap.c:1067)
==8070==    by 0xEB9ADB1: PMPI_Send (libmpiwrap.c:1076)
==8070==    by 0xF4D77F4: PMPI_SEND (in /global/opt/mvapich2/gdr/2.1/cuda7.0/gnu/lib64/libmpifort.so.12.0.5)
==8070==    by 0x6CE40C: mpe_io_open$mpe_io2_ (mpe_io2.f90:814)
==8070==    by 0x60BA45: open_file$io_utilities_ (io_utilities.f90:778)
==8070==    by 0xB63C71: organize_input$src_input_ (src_input.f90:1281)
==8070==    by 0x7D8E91: organize_data_ (organize_data.f90:2360)
==8070==    by 0x652558: main (lmorg.f90:800)
==8070==  Address 0x1ffed72708 is on thread 1's stack
==8070==  in frame #4, created by mpe_io_open$mpe_io2_ (mpe_io2.f90:727)
==8070==.```
