### ISSUE TITLE
Score-P/3.0 on kesch

### ISSUE THREAD

**Issue by jgphpc** [MeteoSwiss-APN/comm_overlap_bench#4]
## Kesch:
> module use /apps/escha/UES/easybuild/modulefiles  
> module load `Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr`

```
Currently Loaded Modulefiles:
craype-haswell
binutils/.2.25
GCC/4.9.3-binutils-2.25
cudatoolkit/7.5.18 <--------------
mvapich2gdr_gnu/2.2_cuda_7.5 <--------------
MVAPICH2/2.2_cuda_7.5_gdr
craype-network-infiniband
gmvapich2/17.02_cuda_7.5_gdr
zlib/.1.2.8
libunwind/.1.1
binutils/.2.26-scorep
libunwind/.1.1-scorep
Qt/.4.8.6
Cube/.4.3.3
papi/5.4.3.2
vampir/9.2.0
```

* $EBROOTSCOREMINP/share/scorep/scorep.summary

Let me know if it fails.

**Comment by jgphpc** [comment]
My srun fails in `scorep_finalize / SCOREP_SynchronizeClocks`:

```
../src/measurement/paradigm/mpi/scorep_ipc_mpi.c:179: 
SCOREP_IpcGroup_GetSize:
Assertion SCOREP_Status_IsMppInitialized() failed.
[keschcn-0011:mpi_rank_1][error_sighandler] 
Caught error: Aborted (signal 6)
```

Same issue with G2G=2 and G2G=1

**Comment by jgphpc** [comment]
Score-P fails in:
![eff](https://cloud.githubusercontent.com/assets/5328644/23621690/12cbfce8-029c-11e7-8f5c-85467fb20f9f.png)

### Score-P/3.0-gmvapich2-15.11_cuda_7.0_gdr
* Boost/1.63.0-gmvapich2-15.11_cuda_7.0_gdr-Python-2.7.12

### Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr
* Boost/1.63.0-gmvapich2-17.02_cuda_7.5_gdr-Python-2.7.12

**Comment by pspoerri** [comment]
When I'm trying to load `Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr` on kesch, I'm seeing this:
```
> module load Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr
Cube(37):ERROR:105: Unable to locate a modulefile for 'Cube/.4.3.3'
Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr(56):ERROR:105: Unable to locate a modulefile for 'vampir/9.2.0'
```

**Comment by jgphpc** [comment]
Try

```
module use /apps/common/UES/RHAT6/easybuild/modules/all
module load Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr
```

**Comment by pspoerri** [comment]
Ok, I'll try. 

Do you realize that this score-p version is using the wrong nvcc version?
```
spoerrip@keschln-0002:/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench> scorep-nvcc --version
WARNING: Found no input files
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
spoerrip@keschln-0002:/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench> which scorep-nvcc
/apps/escha/UES/RH6.7/easybuild/software/Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr/bin/scorep-nvcc
```

**Comment by jgphpc** [comment]
Which cudatoolkit version did you load ?

Currently Loaded Modulefiles:
craype-haswell
Vim/8.0
binutils/.2.25
GCC/4.9.3-binutils-2.25
cudatoolkit/7.5.18
mvapich2gdr_gnu/2.2_cuda_7.5
MVAPICH2/2.2_cuda_7.5_gdr
craype-network-infiniband
gmvapich2/17.02_cuda_7.5_gdr
zlib/.1.2.8
libunwind/.1.1
binutils/.2.26-scorep
libunwind/.1.1-scorep
Qt/.4.8.6
Cube/.4.3.3
papi/5.4.3.2
vampir/9.2.0
Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr

wh nvcc
/global/opt/nvidia/cudatoolkit/7.5.18/bin/nvcc

wh scorep-nvcc
/apps/escha/UES/RH6.7/easybuild/software/Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr/bin/scorep-nvcc

nvcc --version
Cuda compilation tools, release 7.5, V7.5.17

scorep-nvcc --version
Cuda compilation tools, release 7.5, V7.5.17

scorep --version
Score-P 3.0

**Comment by pspoerri** [comment]
This could be the reason, thank you.

**Comment by pspoerri** [comment]
how did you compile with score-p enabled? I'm getting a really annoying error as soon as I use the scorep-nvcc wrapper.

**Comment by jgphpc** [comment]
Prepend
 scorep --cuda --mpp=mpi --keep-files
to mpicxx and nvcc.

I am also using a makefile instead of cmake because i need to link manually
with the attached file.

**Comment by pspoerri** [comment]
I get an error here:
![screen shot 2017-03-07 at 18 14 55](https://cloud.githubusercontent.com/assets/282446/23668642/0a3a5662-0362-11e7-9774-9e4a1b76399f.png)

**Comment by pspoerri** [comment]
I added two new scripts `build_kesch_cuda75scorep.sh` and `run_kesch_cuda75scorep.sh`. I rather prefer to use the cmake interface and get it working there. When we work with the Dycore I do not want to modify the build environment.

Please also note that I had to disable `CUDA_SEPARABLE_COMPILATION` in order for the wrapper to work. This seems to be a bug (https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/17)

**Comment by jgphpc** [comment]
Yes, this is a compilation issue, reported in:
https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/6#issuecomment-282021819

You must move '-lmpi -lmpicxx' up on your link line, there is some
unexplained conflict (with or without scorep). It would help to ask OSU.

jg.

**Comment by pspoerri** [comment]
I don't believe so: I rewrote the cmake script that the CUDA code is compiled into a separate library. I then link everything together:
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/comm_overlap_benchmark.dir/link.txt --verbose=1
/apps/escha/UES/RH6.7/easybuild/software/Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr/bin/scorep-g++   -std=c++11 -g  -lpthread CMakeFiles/comm_overlap_benchmark.dir/main.cpp.o CMakeFiles/comm_overlap_benchmark.dir/MPIHelper.cpp.o CMakeFiles/comm_overlap_benchmark.dir/Repository.cpp.o CMakeFiles/comm_overlap_benchmark.dir/Options.cpp.o  -o comm_overlap_benchmark -rdynamic /opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64/libmpicxx.so /opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64/libmpi.so libStandaloneStencilsCUDA.a /global/opt/nvidia/cudatoolkit/7.5.18/lib64/libcudart.so -Wl,-rpath,/opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64:/global/opt/nvidia/cudatoolkit/7.5.18/lib64:
```

and I'm still getting the segfault in MPI. Do you have your library somewhere?

**Comment by pspoerri** [comment]
I also added `-lmpi -lmpicxx` to the beginning and it did not help (note I'm running on escha):
```
Linking CXX executable comm_overlap_benchmark
cd /scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/build_cuda75/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/comm_overlap_benchmark.dir/link.txt --verbose=1
/apps/escha/UES/RH6.7/easybuild/software/Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr/bin/scorep-g++   -std=c++11 -g  -L/opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64 -lmpi -lmpicxx -lpthread CMakeFiles/comm_overlap_benchmark.dir/main.cpp.o CMakeFiles/comm_overlap_benchmark.dir/MPIHelper.cpp.o CMakeFiles/comm_overlap_benchmark.dir/Repository.cpp.o CMakeFiles/comm_overlap_benchmark.dir/Options.cpp.o  -o comm_overlap_benchmark -rdynamic libStandaloneStencilsCUDA.a /global/opt/nvidia/cudatoolkit/7.5.18/lib64/libcudart.so -Wl,-rpath,/global/opt/nvidia/cudatoolkit/7.5.18/lib64:
make[2]: Leaving directory `/scratch-shared/meteoswiss/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/build_cuda75'
/usr/bin/cmake -E cmake_progress_report /scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/build_cuda75/CMakeFiles  3 4 5 6
[100%] Built target comm_overlap_benchmark
make[1]: Leaving directory `/scratch-shared/meteoswiss/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/build_cuda75'
/usr/bin/cmake -E cmake_progress_start /scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/build_cuda75/CMakeFiles 0
spoerrip@eschaln-0003:/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench> ./run_kesch_cuda75scorep.sh
Cube(37):ERROR:105: Unable to locate a modulefile for 'Cube/.4.3.3'
Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr(56):ERROR:105: Unable to locate a modulefile for 'vampir/9.2.0'
Modules:
Currently Loaded Modulefiles:
  1) craype-haswell                             6) GCC/4.9.3-binutils-2.25                   11) libunwind/.1.1
  2) craype-network-infiniband                  7) cray-libsci_acc/3.3.0                     12) papi/5.4.3.2
  3) cudatoolkit/7.5.18                         8) MVAPICH2/2.2_cuda_7.5_gdr                 13) Score-P/3.0-gmvapich2-17.02_cuda_7.5_gdr
  4) mvapich2gdr_gnu/2.2_cuda_7.5               9) gmvapich2/17.02_cuda_7.5_gdr
  5) binutils/.2.25                            10) zlib/.1.2.8
Running with 2 jobs (set jobs environment variable to change)
Setting special settings for G2G=2

Nodes: 1
Tasks/Node: 2
Tasks/Socket: 2
Partition: debug
StandaloneStencilsCUDA

usage: StandaloneStencilsCUDA [--ie isize] [--je jsize] [--ke ksize] \
                              [--sync] [--nocomm] [--nocomp] \
                              [--nh nhaloupdates] [-n nrepetitions] [--inorder]

MV2_COMM_WORLD_LOCAL_RANK: 0, 1,
CUDA_VISIBLE_DEVICES: [0: 0,1] [1: 0,1]
Configured CUDA Devices: [0: 0] [1: 1]
SLURM_JOBID: 9109279
SLURM_PROCID: 0, 1,
SLURM_CPU_BIND: [0: quiet,mask_cpu:0x000001,0x000002] [1: quiet,mask_cpu:0x000001,0x000002]
SLURMD_NODENAME: eschacn-0012, eschacn-0012,

CONFIGURATION
====================================
Domain : [128,128,60]
Sync? : 0
NoComm? : 0
NoComp? : 0
Number Halo Exchanges : 2
Number benchmark repetitions : 1000
In Order halo exchanges? : 0
Compiled for mvapich2
Dimensions: [2, 1]
Neighbors: [0: 1,0,1,0] [1: 0,1,0,1]
[eschacn-0012:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
[eschacn-0012:mpi_rank_1][error_sighandler] Caught error: Segmentation fault (signal 11)
srun: error: eschacn-0012: tasks 0-1: Segmentation fault (core dumped)
srun: Terminating job step 9109279.0
```

**Comment by jgphpc** [comment]
@cosunae: what's the difference between your files (/scratch-shared/meteoswiss/scratch/cosuna/cosmo-pompa.scorep_nonblockcomm/run/scorep-20170215_2058_620904001155401) and the comm_overlap_bench ?

**Comment by jgphpc** [comment]
### Score-P/3.0-gmvapich2-17.01_cuda_8.0_gdr

* Same issue as reported in https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/4#issuecomment-284471975

```
GNU4.9.3-CUDAV8.0.44-Stencils.kes: 
../src/measurement/paradigm/mpi/scorep_ipc_mpi.c:179: 
SCOREP_IpcGroup_GetSize: Assertion `SCOREP_Status_IsMppInitialized()' failed.
```


> module purge 
> module use /apps/escha/UES/RH6.8_PE17.02/easybuild/modules/all
> module load craype-haswell craype-network-infiniband 
> module load Score-P/3.0-gmvapich2-17.01_cuda_8.0_gdr

```
Currently Loaded Modulefiles:
craype-haswell
craype-network-infiniband
binutils/.2.25
GCC/4.9.3-binutils-2.25
cudatoolkit/.8.0.44
mvapich2gdr_gnu/.2.2_cuda_8.0
MVAPICH2/2.2-GCC-4.9.3-binutils-2.25_cuda_8.0_gdr
gmvapich2/17.01_cuda_8.0_gdr
libunwind/.1.1
Cube/.4.3.4
papi/5.4.3.2
vampir/9.2.0
Score-P/3.0-gmvapich2-17.01_cuda_8.0_gdr
```

* only 1 cnode available (`keschcn-0002`) hence i can not test jobs with only 1 gpu per node

**Comment by pspoerri** [comment]
The main difference is that MPI is run by GCL/STELLA. Other than that it's about the same.

**Comment by pspoerri** [comment]
Ok, I'm starting to have an idea where the problem could be. 

1. First we implemented the MPI_Request parameter for MPI_ISEND because this could have triggered the segfault (http://stackoverflow.com/questions/10882581/mpi-isend-request-parameter ). 
2. Then I implemented a CPU-only mode to check whether the communication actually works (it does). I also tested this version against Score-P to check whether it produces a result: It does! Great!
3. Then I had a look at the code again. What we are doing is a CUDA->CUDA communication through RDMA. So the buffers are allocated only on the GPU (there's a couple of cudaMallocs in the code). Looking at the corefile in ddt shows me a `memcpy`. It seems that this call should be a `cuda_something` instead. Which hints at a MPI/compilation problem. 
![screen shot 2017-03-08 at 19 06 26](https://cloud.githubusercontent.com/assets/282446/23717324/a6be255a-0433-11e7-8445-fa698c1dc784.png)
However, I do not see a problem in the linker (formatted for clarity):
```
[... snip with script ./build_kesch_cuda75scorep.sh ]
/scratch/spoerrip/proj_comm_overlap_bench/comm_overlap_bench/CC.scorep   
-std=c++11 -g    
CMakeFiles/comm_overlap_benchmark.dir/main.cpp.o 
CMakeFiles/comm_overlap_benchmark.dir/MPIHelper.cpp.o 
CMakeFiles/comm_overlap_benchmark.dir/Repository.cpp.o 
CMakeFiles/comm_overlap_benchmark.dir/Options.cpp.o  
-o comm_overlap_benchmark 
-rdynamic 
/opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64/libmpicxx.so 
/opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64/libmpi.so 
libStandaloneStencils.a 
/global/opt/nvidia/cudatoolkit/7.5.18/lib64/libcudart.so 
-Wl,-rpath,/opt/mvapich2/gdr/2.2/cuda7.5/gnu/lib64:/global/opt/nvidia/cudatoolkit/7.5.18/lib64:
```
4. I also made use of the wrappers of @cosunae to double check if we have different results. He has a bit of an inconsistent configuration, which I made consistent (keeping it inconsistent did not help).

**Comment by jgphpc** [comment]
See https://github.com/MeteoSwiss-APN/comm_overlap_bench/pull/25
![eff](https://cloud.githubusercontent.com/assets/5328644/25044693/532d594e-2128-11e7-902c-c83a987e6e30.png)

**Comment by jgphpc** [comment]
### Score-P/3.1 + cuda/75 (G2G=1 vs G2G=2)

* See timings in https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/15
* Blue is G2G=1, White is G2G=2

#### G2G=2 is slower than G2G=1:
![eff0](https://user-images.githubusercontent.com/5328644/27284132-b7575d40-54f7-11e7-9bdc-a6d6924a5520.png)

#### because cuda_malloc is slower in init phase:
![eff2](https://user-images.githubusercontent.com/5328644/27284133-b76128fc-54f7-11e7-9e25-a6c29a46784c.png)

#### and because cudadevsync and mpi_wait take longer with G2G=2:
![eff](https://user-images.githubusercontent.com/5328644/27284131-b7547f08-54f7-11e7-9180-3c3b77f0786d.png)

**Comment by jgphpc** [comment]
### Score-P/3.1 + G2G=1 (cuda/70 vs cuda/75)

* Blue/Right is cuda/75, white/left is cuda/70
* cuda/70 is faster than cuda/75:
![eff](https://user-images.githubusercontent.com/5328644/27285646-9f491382-54fd-11e7-9067-e455e0fa3181.png)

* Traces are in _/project/csstaff/piccinal/cosmo/comm_overlap_bench+sc31/_
* https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/23#issuecomment-309669314

**Comment by jgphpc** [comment]
For reference, see https://github.com/MeteoSwiss-APN/comm_overlap_bench/issues/32#issuecomment-309410310
